language: c
compiler:
  - gcc
before_install:
  - test -n $CC && unset CC
  - sudo apt-get install -y libmpich-dev
  - sudo apt-get install -y libopenmpi-dev
  - sudo apt-get install -y mpich
  - sudo apt-get install -y openmpi-bin
env:
  - OMP_NUM_THREADS=4
  - CODECOV_TOKEN="f38fe413-4e68-4d7b-aafe-4fcdb4fc7420"
script:
  - mpicc mult-matrix-ring-rotation.c -o main -Wall -lm -fopenmp -std=c99
  - mpirun -np 4 ./main example/A example/B